"""add_registration_dates_to_tournament

Revision ID: 13a928ba5104
Revises: 0020_player_user_link
Create Date: 2026-05-19 12:52:54.109961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a928ba5104'
down_revision: Union[str, None] = '0020_player_user_link'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'is_configured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('events', 'max_squad_size')
    op.drop_column('events', 'min_squad_size')
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('players', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('players', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index('ix_standings_event_id', table_name='standings')
    op.drop_index('ix_standings_group_id', table_name='standings')
    op.alter_column('team_members', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_constraint('uq_team_player', 'team_members', type_='unique')
    op.drop_constraint('team_members_player_id_fkey', 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'player_id')
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.drop_constraint('teams_event_id_fkey', 'teams', type_='foreignkey')
    op.drop_column('teams', 'event_id')
    op.add_column('tournaments', sa.Column('registration_start_date', sa.Date(), nullable=True))
    op.add_column('tournaments', sa.Column('registration_end_date', sa.Date(), nullable=True))
    op.drop_column('tournaments', 'banner_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('banner_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'registration_end_date')
    op.drop_column('tournaments', 'registration_start_date')
    op.add_column('teams', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teams_event_id_fkey', 'teams', 'events', ['event_id'], ['event_id'], ondelete='CASCADE')
    op.alter_column('teams', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('team_members', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('team_members_player_id_fkey', 'team_members', 'players', ['player_id'], ['player_id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_team_player', 'team_members', ['team_id', 'player_id'])
    op.alter_column('team_members', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_index('ix_standings_group_id', 'standings', ['group_id'], unique=False)
    op.create_index('ix_standings_event_id', 'standings', ['event_id'], unique=False)
    op.alter_column('players', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('players', 'phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('players', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('events', sa.Column('min_squad_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('max_squad_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('events', 'is_configured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
